### ISSUE TITLE
Firefox - some shortcusts do not work - q, A, Ctrl+R etc

### ISSUE THREAD

**Issue by tomas-ab** [mgsloan/todoist-shortcuts#46] opened 2018-10-01 09:26 UTC
Thanks for this useful extension. I noticed that some shortcusts q, A, a does not work, while g, k, j,d,t etc. do work as well as o. 
O, o works but just add tasks at the bottom always, irrespective of cursor placing. 
Firefox shortcuts like CTRL+R or F5 do not work on todoist page. On all other pages, CTRL+R, F5 work. 
I use Firefox 62.0.2

**Comment by Nikovic** [comment] 2018-10-01 16:01
I just installed the extension, so I don't even know what a lot of those keys do, but I can offer the reason for 'h' and 'l' not working:
The arrrows that collapse/expand the tasks or projects used to have the classes 'cmp_open_arrow_down' and 'cmp_open_arrow_right' respectively. That has recently been changed to 'arrow down' and 'arrow right' respectively.

**Comment by mgsloan** [comment] 2018-10-01 20:11
@tomas-ab Glad you enjoy it!  Are you sure that your todoist-shortcuts version is up-to-date?

@Nikovic Good catch.

**Comment by tomas-ab** [comment] 2018-10-02 14:44
I have removed and added the extension todoist shortcuts now and the issue still persits.

**Comment by mgsloan** [comment] 2018-10-02 18:33
@tomas-ab Ohhh yes, I can also reproduce the issue on firefox 62.  Hmm

I guess the hack fix in https://github.com/mgsloan/todoist-shortcuts/commit/f62c4838ef521d959414c9e17cb45c4726f3a224 did not resolve the problem for fallthrough to the original keybinding.  Not sure what to do about this, puzzling that firefox and chrome are behaving differently for something as "simple" as keyboard input

**Comment by mgsloan** [comment] 2018-10-20 20:55
Sorry for the long delay in fixing this, but I finally figured it out!  Rather shocking that `fn.apply` would behave differently in chrome vs firefox, perhaps something more subtle is going on.  One way or another, this appears to be fixed in version 31.

**Closed by mgsloan** 2018-10-20 20:55 UTC
Labels: bug, help wanted

**Comment by tomas-ab** [comment] 2018-10-24 13:20
This is great news. Many thanks, I will buy a coffee, really appreciate your work!

**Comment by mgsloan** [comment] 2018-10-25 19:03
Thanks @tomas-ab ! Glad that you appreciate it.
