### ISSUE TITLE
Lost focus during 'open task view' function

### ISSUE THREAD

**Issue by thenobody14** [mgsloan/todoist-shortcuts#114] opened 2020-04-01 10:47 UTC
In version 991 of the Todoist web application, when I use keyboard shortcut `i` to open the task view, the focus appears to be on the parent task element within the UI (blue square in screenshot). This means that none of the context-specific keyboard shortcuts work (e.g. `s`, `c`, `h`).

![image](https://user-images.githubusercontent.com/54414085/78128462-e397e180-740d-11ea-9286-f2ba808e6712.png)

I am using Google Chrome 80.0.3987.149 on PC

Thanks for your time.

**Comment by idonimni** [comment] 2020-04-05 11:09
I experience the same issue.

**Comment by mgsloan** [comment] 2020-04-05 18:37
This is weird, it appears to be a change in Todoist's behavior, but it only happens when clicking the task via a keyboard shortcut, and not when clicking a task with the mouse.  I have reproduced the problem in the developer console, though, by selecting a task `li` element and doing `$0.click()` on it - this causes the same result of the parent button being focused.

I've pushed an attempt at a workaround to a branch - https://github.com/mgsloan/todoist-shortcuts/tree/blur-task-view-parent-114 .  It works the first time the task view is opened, but after that the task view *never* opens.  Somehow sending the blur event to the parent button is breaking Todoist's task view, I can't even open it with the mouse.

**Comment by mgsloan** [comment] 2020-04-06 03:32
Nevermind, it turned out that the focus on the button is benign and caused by the keyup event, going to leave it that way for now.

I'm not sure exactly what was broken, but it was due to squirreliness in keyboard handling.  By changing that to be more straightforward, it appears to work now!  Not yet released.

**Comment by mgsloan** [comment] 2020-04-06 04:06
This was tricky, I believe I've fixed it!  The fix is included in version 77.

The unsatisfying part is that I'm still not sure exactly what was going on, just that it was fiddlyness in the keyboard handling.  The satisfying part is that the dispatch for the keyboard input handling is now a lot more sensible.

**Closed by mgsloan** 2020-04-06 04:06 UTC
Labels: bug

**Comment by thenobody14** [comment] 2020-04-06 12:51
Sorry to bring this back up, but I've updated to version 77 and am still experiencing this issue. I restarted the browser and did an 'empty cache and hard reload' of Todoist, but still experience the issue.

Let me know if there's anything that I can provide to help with troubleshooting.

**Comment by mgsloan** [comment] 2020-04-06 16:39
No worries, I should clarify that the parent button will still be focused.
However, now the keyboard shortcuts should work in task view.  Do the
shortcuts still not work?

**Comment by thenobody14** [comment] 2020-04-06 19:47
Ah yes. You're quite right. Sorry, I hadn't actually attempted the shortcut keys.

Thank you very much for creating this extension and for the prompt resolution of this issue. I have bought you a coffee. :)

**Comment by mgsloan** [comment] 2020-04-06 21:26
You're welcome!  Thanks for showing your appreciation :)
