### ISSUE TITLE
Extension breaks web app sync

### ISSUE THREAD

**Issue by ianmalott** [mgsloan/todoist-shortcuts#60] opened 2019-02-03 20:14 UTC
When using the [Todoist web app](https://todoist.com/app) with the [Todoist Shortcuts extension](https://chrome.google.com/webstore/detail/todoist-shortcuts-gmail-v/dehmghpdcahlffompjagejmgbcfahndp) enabled in Chrome, actions taken from another Todoist app (Android and web confirmed) do not get synced automatically to the current Todoist web app. Disabling the extension and then reloading the web app restores the expected sync functionality.

**Steps to reproduce**
1. Open Today view in web app A and web app B.
2. Ensure Todoist Shortcuts extension is enabled for web app A.
3. Complete a task in web app B.
4. Notice that the task remains uncompleted in web app A.

Thanks for creating and sharing such a useful extension! Let me know if I can help with further debugging.

**Comment by mgsloan** [comment] 2019-02-05 09:57
Good catch, thanks for reporting!

I can reproduce the problem, but after fiddling with it for a while, curiously sometimes the syncing does work, albeit usually after an abnormally long wait.  I tried commenting out a few likely suspects, and found that commenting out the top level call of `registerTopMutationObservers` resolves the issue.  It's a total mystery to me.

Here's what the stack of the handler for `sync` looks like when it works (it seems to start a timer that later does a render, or something like that):

![image](https://user-images.githubusercontent.com/22570/52265554-3567d900-28e9-11e9-955c-ceca1de6f2b6.png)

Whereas here is the stack of a broken sync:

![image](https://user-images.githubusercontent.com/22570/52265583-444e8b80-28e9-11e9-8dbf-061689591809.png)

Pretty similar, but some differences.  I think this is likely an upstream Todoist bug, I don't think todoist-shortcuts is doing anything particularly wrong, I'm guessing it's just changing some timing characteristics to make the bad behavior more likely.

**Comment by ianmalott** [comment] 2019-02-06 23:52
Thanks a lot for taking a closer look. I let Todoist support know about this issue and mentioned that it'd be great if one of their developers could chime in here. I wouldn't expect that to happen, but you never know.

**Comment by mgsloan** [comment] 2019-02-08 01:38
:+1: A temporary workaround for now is that there is a binding for manually syncing - `ctrl+s`

**Comment by mgsloan** [comment] 2019-02-11 11:50
Hmm actually manual sync doesn't seem to do the trick.  Curious!

**Comment by stkao05** [comment] 2019-02-14 16:42
Just installed the extension but can't seem to reproduce this issue 🤔

@ianmalott @mgsloan 
From the request log, could you see if sync gets automatically triggered at first place?

**Comment by ianmalott** [comment] 2019-02-15 03:41
Hi @stkao05, thanks for taking a look. I was able to confirm the original reported issue in version 44 of the extension, but it looks like the issue is partially fixed in version 45, which was released within the past day. That may be why you weren't able to reproduce the issue. Here's some inconsistent sync behavior I'm still seeing in version 45:

**Adding a new task**
This operation now gets synced as expected.

**Deleting a task**
This operation seems to not sync until a mouse hover event in the out-of-date app triggers a sync. This may be intentional behavior, but it doesn't match the sync behavior for other operations, like adding a new task. Plus, if your goal is to keep your hands on the keyboard, you might not move the mouse at all, and therefore not trigger a sync incidentally with a hover.

**Updated (version 45) Steps to reproduce**

1. Open Today view in web app A and web app B.
2. Ensure Todoist Shortcuts extension is enabled for web app A.
3. _Delete_ a task in web app B.
4. Don't move your mouse around in web app A.
5. Notice that the task remains _not deleted_ in web app A for up to a few minutes, maybe indefinitely.
6. Now move your mouse over various elements in web app A and notice the sync finally occur.

**Comment by mgsloan** [comment] 2019-02-17 08:22
In my prior investigation, the behavior seemed to occur quite a bit less when I disabled some dom mutation observers. This leads me to believe that it's due to particulars of execution scheduling / timing, and that perhaps the problem is the unexpected delays due to the mutation observers.

It isn't surprising that this changed in version 45, because https://github.com/mgsloan/todoist-shortcuts/commit/2f17b9c5f2a8939632221c06551aa69c3267a4e8 does some intelligent filtering of some of the most common ignorable dom mutations.

**Comment by mgsloan** [comment] 2020-08-20 06:45
Closing out as an old bug

**Closed by mgsloan** 2020-08-20 06:45 UTC
Labels: upstream-bug, wontfix
