### ISSUE TITLE
Task navigation broken/disabled with new 'Upcoming' View

### ISSUE THREAD

**Issue by abelthomas** [mgsloan/todoist-shortcuts#126] opened 2020-04-30 10:50 UTC
Todoist just replaced 'Next 7 Days' view with a new, 'Upcoming' view. Unfortunately, with that update, I no longer see the blue task cursor on the left side of highlighted tasks. 

Since `j`/`k`/`h`/`l` and `Shift + [`/`Shift + ]` are in my heavy rotation for navigating tasks and sections, this is a really unfortunate bug. Would love to get this functionality back!

**Comment by mgsloan** [comment] 2020-04-30 17:47
Thanks for reporting, yeah it's not great.  I was hoping that Todoist's task list rendering would become more homogenous before the upcoming view got pushed to todoist.com, but that didn't happen.  So now the extension needs to support two very different DOM structures.

Duplicate of #110

**Closed by mgsloan** 2020-04-30 17:47 UTC
